### ISSUE TITLE
[FEATURE] Loading n64 roms from network

### ISSUE THREAD

**Issue by animekai** [Rinnegatamante/DaedalusX64-vitaGL#1]
It would be great to implement loading roms from network, like a shared folder from pc or a NAS, the fullrom set of n64 games is 5gb, but our memory cards will thank us to not use that space if we load roms from another storage.

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/39dc3bf6a7ae18cc889c146a3b52cfebcbd815b6
