### ISSUE TITLE
[FEATURE] Image Background for the menu

### ISSUE THREAD

**Issue by animekai** [Rinnegatamante/DaedalusX64-vitaGL#100]
Woul be nice to have a default image in the background menu, or a option to use external images for the menu, it get boring to see black solid backgrouns, maybe a preset to have the list of games to be not covered or difused by the BG image.

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/ece6919ea3789e32622c9934ff4c95a86ade4b81
