### ISSUE TITLE
[FEATURE] Music Background for the menu

### ISSUE THREAD

**Issue by animekai** [Rinnegatamante/DaedalusX64-vitaGL#101]
Would be nice to have some relaxing music BG in the menu (elevator music XD), some default tunes or the option have external mp3 ogg etc music BG.

pd: maybe some sounds when key are pressed or menus sound effects.

**Comment by bielgiroto** [comment]
I miss that on the Vita emulators, PSP ones used to have some, it was very cool :p

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/07a170111db9687afcb9b068b4c1641d67a7429d
