### ISSUE TITLE
[FEATURE] Accessing roms from uma0: 

### ISSUE THREAD

**Issue by f2pwn** [Rinnegatamante/DaedalusX64-vitaGL#102]
Could we have DaedalusX64 accessing uma0 so we can load roms from memory stick?

**Comment by Rinnegatamante** [comment]
Partially done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/4e8ed2de34ede49633e8fad5496638bdb069e21f (Allows fullpath usage in custom bubbles with ux0 and uma0 support)

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/f640dad74d751d58935eba111bf01f5b39caee18
