### ISSUE TITLE
[BUG] Paper Mario crashes when loading a new file.

### ISSUE THREAD

**Issue by zeddy1267** [Rinnegatamante/DaedalusX64-vitaGL#105]
Unable to load or start a new save file on Paper Mario with the nightly build, but it works fine in regular build. Starting any file results in an error screen, while DaedalusX64 0.3 can do it just fine. If you have a save state in game though, you can load it, and the game has so far been completely playable (I'm not even sure if saving is possible with any game yet.) I understand the nightly build is not a stable release, but I wouldn't want this error to make it into whenever the next build is.
![20200611_224936](https://user-images.githubusercontent.com/25875170/84470245-c5353a00-ac37-11ea-937d-7016e807821a.jpg)

This DaedalusX64 build is 2020611.1, but this issue was in older nightly builds as well (I don't know when exactly this started, sorry.) My vita is the 1000 model, running 3.60

**Comment by Rinnegatamante** [comment]
Please report game specific issues in the compatibility list: https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/13
