### ISSUE TITLE
[FEATURE] Extra triggers grip support

### ISSUE THREAD

**Issue by JuanVCS** [Rinnegatamante/DaedalusX64-vitaGL#106]
It would be nice to have L2/R2/L3/R3 support, for those of us using something like the [Hori Remote Play Attachtment](https://www.amazon.com/HORI-Vita-Remote-Assist-Attachment/dp/B01ERA94BY).

**Comment by Rinnegatamante** [comment]
Can you tell me (by using a test app like https://vitadb.rinnegatamante.it/#/info/121 ) what coordinates do you get when pressing L2/L3/R2/R3?

**Comment by JuanVCS** [comment]
L2
![L2](https://user-images.githubusercontent.com/3089037/84823138-40aa3900-aff4-11ea-8ea3-6009c289499b.jpg)

L3
![L3](https://user-images.githubusercontent.com/3089037/84823141-41db6600-aff4-11ea-9170-98ef28edd8b7.jpg)

R2
![R2](https://user-images.githubusercontent.com/3089037/84823143-4273fc80-aff4-11ea-893a-a80f73812159.jpg)

R3
![R3](https://user-images.githubusercontent.com/3089037/84823145-4273fc80-aff4-11ea-9517-6a437788a0c2.jpg)

**Comment by Rinnegatamante** [comment]
Can you join the Discord server? I have a test build with support for this that requires a test.

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/d52a15f2c84c5601872e332ce7e66f919d32d77b
