### ISSUE TITLE
[BUG] Perfect Dark (USA) (Rev 1) Doors Cannot Be Opened

### ISSUE THREAD

**Issue by JamesSDK** [Rinnegatamante/DaedalusX64-vitaGL#107]
Description:
After a few minutes of gameplay the B Button stops opening doors and interacting with objects. 

Steps to Reproduce:
No specific action reproduces the bug on demand it will just happen after about 4-5 minutes of playing the game but it always will occur.

I am using Video Frame Sync, Texture Cache (Fast),  Synchronus Audio and Disable MP3 Instructions. Controller is set to Gamecube Triggers Swapped. 

Expected behavior:
The B Button should work 100% of the time when attempting to open doors or use computer terminals. 

Device:
 - Device: Vita Slim
 - FW: 3.60
 - Daedalus Version June 12, 2020 Nightly.

Additional context:
When the issue occurs it affects all areas of the game (single player, multiplayer, training areas) and all doors and interactive objects like computer terminals. Reloading which also uses the B Button is not affected.

Issue does not occur using the same ROM in Retroarch 1.8.8 for PC and Android (all N64 cores) or N64oid.

**Comment by Rinnegatamante** [comment]
For game specific bugs, refer to the compatibility list report for said game and report the issue there: https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/115
