### ISSUE TITLE
Pachinko 365 nichi Upside down

### ISSUE THREAD

**Issue by pirotantan** [Rinnegatamante/DaedalusX64-vitaGL#126]
![DaedalusX64_0 3](https://user-images.githubusercontent.com/65655212/85208163-27451c00-b369-11ea-879b-2e3b28e9f24c.jpg)
![DaedalusX64_0 2](https://user-images.githubusercontent.com/65655212/85208164-28764900-b369-11ea-8d47-ca22a3e7998b.jpg)

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues
Game specific reports go here.
