### ISSUE TITLE
Search on big list of games

### ISSUE THREAD

**Issue by animekai** [Rinnegatamante/DaedalusX64-vitaGL#129]
As having a big list of games, in this case, all n64 games, the scrolling to search games is kindda slow, maybe devs can increase the scrolling speed, or assign a L R button to skip to next page to get a fast scroll, or a search box to get a specific game, this is not a problem with a few games obviously, but with large list of games is a bit difficult to get a game. Would be nice to ease this process.

**Comment by Rinnegatamante** [comment]
The L and R button page was already suggested. I'll leave this issue opened for the Search feature.

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/f37a09fa2d62335755cfb8400b89fea9dc5e8f49
