### ISSUE TITLE
Loading game message.

### ISSUE THREAD

**Issue by ThePhoenixRises** [Rinnegatamante/DaedalusX64-vitaGL#140]
I would just like to see an improvement in the UI, as in having the screen clear and a message simply saying, game loading on screen.
As i find having no sign that a game has started or not, annoying, sometimes the game is running when selected (Left trigger),
sometimes it doesn't, but have no way of knowing.
Thank you, for an awesome emulator, keep up the good work.

**Comment by Rinnegatamante** [comment]
We recently added alerts for savestates and settings save/load (it will show a text on bottom left of the screen). I guess this can be applied to roms loading too for those willing to work on this issue.

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/0d4c5b7d0c62381c7cccdfc60be1051aa514d9fd
