### ISSUE TITLE
Missing textures on F-Zero X

### ISSUE THREAD

**Issue by tabnk** [Rinnegatamante/DaedalusX64-vitaGL#161]
Describe the bug
Car model missing texture.

To Reproduce
On the start of any race.

Expected behavior
Must have texture 
Screenshots
Device:
 - Device: VITA
 - FW:3.65
 - Daedalus Version Latest

Additional context

**Comment by Rinnegatamante** [comment]
Game reports are to be submitted on compatibility list: https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues (Also don't open a new issue if the game has already a report but just add a comment)
