### ISSUE TITLE
Crash on newest nightly

### ISSUE THREAD

**Issue by kaymynd** [Rinnegatamante/DaedalusX64-vitaGL#163]
The crash occurs when hovering the pointer over any game after switching the custom roms path to uma0:Roms/N64

**Comment by koutsie** [comment]
+1

**Comment by Rinnegatamante** [comment]
add a final "/" to the rom path and see if it fixes the issue.

**Comment by kaymynd** [comment]
That did fix it! Thank you very much!

**Comment by koutsie** [comment]
very odd but interesting issue, +1 for the fix
maybe add something that sanitizes the path, idk

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/c7483a806e582b0a766ab1d44a5cf1a4cab3617b

**Comment by kaymynd** [comment]
Seems to crash when updating rom path, and again when pointer is above any rome file name in newest nightly
