### ISSUE TITLE
Help with Mario Kart 64 on Vita

### ISSUE THREAD

**Issue by ErectricBass** [Rinnegatamante/DaedalusX64-vitaGL#164]
Whenever I finish a cup (all 4 tracks) on the DaedalusX64 emulator on my Ps Vita the screen goes completely black with distorted sound and I am forced to reset the game. I have tried different cups and racers and the same thing happens. Another thing is that none of my time trial times save.
Just play a cup.

The screen will go black and the sound will become distorted when you get to the final scoring screen after the cup.

Ps Vita 1000
3.60 Henkaku 
Daydalux for Vita v1.3
Website says it’s fully playable.

**Comment by Rinnegatamante** [comment]
Game specific bugs need to be posted in compaitbility list on the specific game issue: https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/2
