### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by plt2so6bis** [Rinnegatamante/DaedalusX64-vitaGL#165]
Describe the bug
The menu cheats has disappear it's has been worked but since I reload the app there is no more menu cheats
Ok it's just the case for sm64 the cheats menu has working one time and now it's disappear for this game but reappear when I launch another game and I've uninstall et reinstall deadalus but nothing change the menu doesn't reappear at all with this game and I've notice that the cover doesn't work anymore with this game.. 

Device:
 - Device: vita 
 - FW:3.60 enzo
 - Daedalus Version 0.4

**Comment by Rinnegatamante** [comment]
Not every game has cheats. Daedalus.cht file is the cheats database.

**Comment by plt2so6bis** [comment]
Sm64 has cheat because it's working one time for this game...
