### ISSUE TITLE
[FEATURE] Custom Roms Path - edit current path setting

### ISSUE THREAD

**Issue by Sulter** [Rinnegatamante/DaedalusX64-vitaGL#166]
I would suggest that clicking the Custom Roms Path, should let you edit the current path, instead of starting with a blank input.
This would make it easier to adjust paths

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/e1e329913df0ddd7fc63954d659d57038343f6f1
