### ISSUE TITLE
[BUG] Shadders affecting overlays and GUI menu

### ISSUE THREAD

**Issue by animekai** [Rinnegatamante/DaedalusX64-vitaGL#173]
When selecting shadders for post processing, those affects the overlays and the menu itself, maybe it can be fixed to shadders only affect the gameplay but not the overlays or menu?

To Reproduce
when in game select a post processing shadder, and this affects everything instead just the gameplay

Expected behavior
Not to affect menus or overlays

Screenshots

![2020-07-25-192846](https://user-images.githubusercontent.com/32076097/88464461-7d354400-ce80-11ea-93d5-169e5c602a8b.jpg)

Device:
 - Device: PSTV
 - FW: 3.60
 - Daedalus Version 0.4 (61e202)

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/1e9a554462b3a202b7567028bc2f0f438d778e3e
