### ISSUE TITLE
[BUG] Extreme-G XG2 CRC issues

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL#181]
Describe the bug
CRC is wrong 

To Reproduce
Get a USA version of Extreme-G XG2
Load game

Expected behavior
Tags loads

Issue is in the roms.ini

{0b15d45cf1c20c47-45}
Name=Extreme-G XG2
Preview=Exteme_G_XG2.png

but according to the emulator the CRC doesn't have the 0 at the beginning

b15d45cf1c20c47-45

So I'm not sure if the crc is wrong in roms.ini or the one generated by the emulator

Additional context

**Comment by Rinnegatamante** [comment]
The CRC is correct. The tags do not show cause the issue title was wrong on the compat. list.
