### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gman2431** [Rinnegatamante/DaedalusX64-vitaGL#187]
I installed the most recent daedalusx64 version to my vita. It was working fine but now all of a sudden out of nowhere whenever i try and open the app i just get error (C2-12828-1) Saved Core File Succeeded. ux0:data/psp2core-1523930768-0x00001222439-eboot.bin.psp2dmp

Device:
 - Device: vita 2000
 - FW: 3.60
 - Daedalus Version beta V0.4

Additional context

**Comment by Rinnegatamante** [comment]
Update to latest nightly vpk.

**Comment by gman2431** [comment]
How do i update to the lastest nightly vpk? I tried downloading the daedalusx64 vpk again from vitadb and reinstalled it but im assuming you mean something else?

**Comment by gman2431** [comment]
> Update to latest nightly vpk.

How do i do this? I tried downloading the vpk again from vitaDB and reinstalled it but im assuming you mean something else?

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/DaedalusX64-vitaGL/releases/tag/Nightly

**Comment by gman2431** [comment]
> https://github.com/Rinnegatamante/DaedalusX64-vitaGL/releases/tag/Nightly

WOW Thank you so much! It fixed it!
