### ISSUE TITLE
[FEATURE REQUEST] Screenshots

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL#188]
Implement screenshot functionality in the emulator.

The built in Vita one directory structure is shit and it'd be good to have one named with the game to make it easier.

SuperMario64-iso8601.jpg

And not sure if you can make the screenshot higher quality too

**Comment by Rinnegatamante** [comment]
There are plugins that do deal with bad naming and/or image compression.
