### ISSUE TITLE
[FEATURE] Add build info in daedalus menu

### ISSUE THREAD

**Issue by animekai** [Rinnegatamante/DaedalusX64-vitaGL#189]
Would be nice to have the version and build name next to daedalus x64 big name, like in this picture

![](https://media.discordapp.net/attachments/698956074216063197/739202652340224000/2020-08-01-141724-158822.png)

It could be usefull for recognize build versions quickly

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/a7d0ab629c81d018cd6e7fd612d0dbed7695822e
