### ISSUE TITLE
[FEATURE] Switch between modern and legacy renderers at runtime

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL#191]
Be able to switch between legacy and modern renderers will make it easier to test and also get into games.

E.g. 
Modern for menus.
Legacy for gameplay

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/064572b6b306fa895def76c7b9a8e6c27e465fbd
