### ISSUE TITLE
[FEATURE] Game play time or percentages of progress  

### ISSUE THREAD

**Issue by Titiclash** [Rinnegatamante/DaedalusX64-vitaGL#197]
Hi Rinne,

as we speak, a suggestion to add in DaedalusX64 the "game play time in the game menus" or if possible "percentages" of game progress

good job

**Comment by bielgiroto** [comment]
Óia a folga do cidadão kkkkk
Vc por aqui homi?

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/5906e2cbc4f3595406754eb0913e36d6fb8a6d27

**Comment by Titiclash** [comment]
Incredible, great job
