### ISSUE TITLE
An error has ocurred (C2-12828-1)

### ISSUE THREAD

**Issue by MalekThaus** [Rinnegatamante/DaedalusX64-vitaGL#202]
when oppening the app my ps via continues to throw this error

it says:

(C2-12828-1)
Saved core file succeeded
ux0:data/psp2core-1597367052-0x00002a3047-eboot.bin.psp2dmp

**Comment by HELLOcommaWORLD** [comment]
Download nightly vpk.

**Comment by Rinnegatamante** [comment]
Stop opening the same issues again and again.
https://github.com/Rinnegatamante/DaedalusX64-vitaGL/issues/199
https://github.com/Rinnegatamante/DaedalusX64-vitaGL/issues/187
