### ISSUE TITLE
[FEATURE] Fast Foward and Rewind combo buttons

### ISSUE THREAD

**Issue by animekai** [Rinnegatamante/DaedalusX64-vitaGL#21]
Would be nice to have a combo buttons to have fast foward and rewind, some games are slow, but fast forward would allow to speed them up and skip boring parts like traversing the map, and the rewind option would help us if we fail in some situation and redo it again, like the dagger of time from POP, rewinding time.

**Comment by Rinnegatamante** [comment]
Rewind would be almost impossible (there's savestate to achieve the same thing) however fast forward is definitely doable.

**Comment by Rinnegatamante** [comment]
Fast-forward added with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/bcb3d24d967d48d26942c815b25d1559c3aad8ad . Closing this since the rewind feature is pretty much impossible to implement.
