### ISSUE TITLE
[FEATURE]translating to Russian language

### ISSUE THREAD

**Issue by nekita13** [Rinnegatamante/DaedalusX64-vitaGL#215]
Hello, I want to offer a translation of this program into Russian. I have a ready-made translation- https://github.com/nekita13/rusufikator_DaedalusX64-vitaGL hope that you will add its main version.
This is how it looks.
![0-02-0a-c5e4aaa8670f846f090a77b2ba9140e94ba658139b9f0598218a490179118cbf_e1966d62](https://user-images.githubusercontent.com/62207719/97511494-a8a85d00-19a0-11eb-8ad8-2c51bdbb416d.jpg)

**Comment by Rinnegatamante** [comment]
If you know how to do a Pull Request, do it and i'll merge it. If not, link me to the translation file and i'll integrate it asap. Btw good job with it ;)

**Comment by nekita13** [comment]
> If you know how to do a Pull Request, do it and i'll merge it. If not, link me to the translation file and i'll integrate it asap. Btw good job with it ;)

I am using github for the first time)) Here is a link to a Google drive with a file https://drive.google.com/file/d/15yc6dish4szwq2RbXLkL7WV_-65jS2Gy/view?usp=sharing
P.S. Sorry for my English.

**Comment by Rinnegatamante** [comment]
Can you give me a translation for the word "Russian" in russian for the language selector option?

**Comment by nekita13** [comment]
> Can you give me a translation for the word "Russian" in russian for the language selector option?
Русский

**Comment by Rinnegatamante** [comment]
Now live on Nightly build: https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/048fa87774b6e494ce55610e5ff096965fb6c76e
