### ISSUE TITLE
Smash Remix mod black screen glitch at multiplayer map selection

### ISSUE THREAD

**Issue by Purplstuph** [Rinnegatamante/DaedalusX64-vitaGL#216]
Describe the bug
The game starts completely normally just like smash 64. Singleplayer works fine as i don't need to select maps.
In multiplayer, the character select screen has a few missing rosters except for the first line (though all is fine from there). 
Then i press start for the map selection and the music glitches out and no screen shows up. I cant go back to character select, forcing me to close the rom.

To Reproduce
Try a multiplayer match and choose a map. But there's nothing except for a black screen and glitching music

Expected behavior
Just like regular smash 64 on multiplayer map selection

Screenshots
![2020-10-29-172758-609238](https://user-images.githubusercontent.com/25884077/97635514-de375f80-1a0d-11eb-8fff-ed2ade22e9ef.png)
![2020-10-29-172816-961136](https://user-images.githubusercontent.com/25884077/97635524-e0012300-1a0d-11eb-8162-b41c4e3a5f1d.png)

Device:
 - Device: PS VITA
 - FW: 3.60
 - Daedalus Version Nightly 20201029.1

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility
