### ISSUE TITLE
[FEATURE] Allow High Resolution Textures

### ISSUE THREAD

**Issue by animekai** [Rinnegatamante/DaedalusX64-vitaGL#22]
The are some many games like mario64 tlozoft banjo kazooie and more, who have new high res textures, can it be possible to use those new textures or some how, would be nice to have those games in a new look high res

There is a pack with all high res textures, i dont now if i can post here the link "http://www.mediafire.com/file/1q2fg8drqulm4dl/hires_texture.rar/file"
if not plz edit this or tell me to delete it.

maybe it can be implement into the realease vpk, or be a extra vpk installer for HD textures i don't now

**Comment by Invictaz** [comment]
Here is the tool to implement them. 

https://github.com/emukidid/Wii64/releases/tag/texturepacker_1.2

**Comment by Invictaz** [comment]
Ocarina of Time High Res Texture pack (updated frequently)

https://evilgames.eu/texture-packs/oot-reloaded.htm

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/bf6be3123460878b0a37606d0ed1e65fb41b4709

**Comment by bielgiroto** [comment]
Wow! I tought this would take a lot of time to be added

And it just got available yesterday!!!!
That's awesome

**Comment by bielgiroto** [comment]
@Rinnegatamante How i can add them? Sorry but I've been messing with this for some time and i don't know how to get it working

**Comment by Rinnegatamante** [comment]
More info will come in the near future on how to set up a texture pack.
