### ISSUE TITLE
[BUG] Modern Renderer - Blank screen with sound.

### ISSUE THREAD

**Issue by tabnk** [Rinnegatamante/DaedalusX64-vitaGL#223]
Describe the bug
**Modern Renderer - Blank screen with sound.**

To Reproduce
**Select Modern Renderer**

Screenshots
Blank Screen

Device:
 - Device: [VITA OLED]
 - FW:[Current System Firmware]
 - Daedalus Version [0.6]

Additional context
SceShaccCg installed via ShaRKF00D.

**Comment by Rinnegatamante** [comment]
That's a game specific bug or an installation issue since most games do run fine with modern renderer.

**Comment by tabnk** [comment]
libshacccg.suprx already installed at ur0:data. What more to the installation need?

**Comment by Rinnegatamante** [comment]
Delete ur0:data, recreate it manually, and transfer back the suprx manually.

**Comment by tabnk** [comment]
Deleted ur0:data folder. And let ShaRKF00D recreated new one. Even deleted the ux0:data folder and Recreated a new one. Uninstalled the DaedalusX64-vitaGL and reinstalled the latest VPK. 

Still same BLANK screen with sound when Modern Renderer is selected. Only Legacy renderer is working. 

MD5 libshacccg.suprx **b95b0617057d24d611ace1cdc0131db8**
