### ISSUE TITLE
[BUG] Only allow Save States for the right game

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL#224]
Describe the bug
It is possible to load the save state for a different region for the same game

To Reproduce
Save state for EU Mario 64, be able to load the US Mario 64

Expected behavior
The states shouldn't be available for the US Mario 64 ROM

Screenshots

Additional context
Assign the states to CRC rather than name.

**Comment by Rinnegatamante** [comment]
This change will however make all previous savestates "invalid" (user will have to manually adjust filename to include CRC).

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/3bcdc262d8fe5bba669ab3e9fe63303fac7763cd
