### ISSUE TITLE
[BUG] Sound issue when playing SmashRemix

### ISSUE THREAD

**Issue by Galel** [Rinnegatamante/DaedalusX64-vitaGL#225]
Describe the bug
The sound seems broken when play Smashremix, with “Zzzzlazzzzzla” all the time. The original US version rom have similar problem but 

To Reproduce
just play smashremix or original smash 64(US).

Expected behavior
The sound should be fine like other roms that I tried(mario 64, zelda, they seems no problem at all).

Screenshots
No need for screenshot though, maybe I could record a sound file with my phone if you need it.

Device:
 - Device: [VITA slim]
 - FW:[3.68]
 - Daedalus Version [0.6]

Additional context
Thank you for your hard word to make the possible!

**Comment by Galel** [comment]
You can look at this vedio, the background and other graphic seem have glitches too. 
https://user-images.githubusercontent.com/4412842/102890900-316ee100-4498-11eb-8a09-f8a513d0eb6a.mov

**Comment by Rinnegatamante** [comment]
Game specific issues must be reporteed in the compatibility list repository in the game specific issue: https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/33

**Comment by Galel** [comment]
> Game specific issues must be reporteed in the compatibility list repository in the game specific issue: https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues

Thanks for mentions, maybe you can specify that in the main page. I’ll put it to https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues though.
