### ISSUE TITLE
[BUG] Crashlog 0.6

### ISSUE THREAD

**Issue by Invictaz** [Rinnegatamante/DaedalusX64-vitaGL#228]
Describe the bug
Switching config in 0.6 F1 Racing Championship gives a C2 error and Daedalus shut's itself down

To Reproduce
It's difficult

Expected behavior
I was hoping that the game would resume emulation

Device:
 - Device: Vita 1000
 - FW: 3.60 enso
 - Daedalus Version 0.6

[psp2core-1611022804-0x00014726f7-eboot.bin.zip](https://github.com/Rinnegatamante/DaedalusX64-vitaGL/files/5833240/psp2core-1611022804-0x00014726f7-eboot.bin.zip)

**Comment by Rinnegatamante** [comment]
Some configs can't be changed during emulation (eg: CPU emulation mode)
