### ISSUE TITLE
Non Transparant water in Metal Cap stage, Super Mario 64 [BUG]

### ISSUE THREAD

**Issue by Deadfalt999** [Rinnegatamante/DaedalusX64-vitaGL#229]
Describe the bug
The water in the metal cap stage isn't transparant, I can't see where I swim with mario.

To Reproduce
Steps to reproduce the behavior: Just go to the Metal Cap switch stage.

Expected behavior
Water should be transparant.

Device:
 - Device: Ps Vita
 - FW: 3.65
 - Daedalus V.0.6 (cfc216)

**Comment by Rinnegatamante** [comment]
That's a game dependant bug, not a generic emu bug. Please report it on the compatibility list.
