### ISSUE TITLE
[FEATURE]Language support

### ISSUE THREAD

**Issue by CHN-Gen** [Rinnegatamante/DaedalusX64-vitaGL#234]
Like most Chinese people, my English is not very good, so i hope to add Chinese translation. Here is my translation. Hope to get support. Thank you!!

STR_DOWNLOADER_COMPAT_LIST=下载兼容性列表数据库
STR_DOWNLOADER_UPDATE=下载更新
STR_DOWNLOADER_CHECK_UPDATE=检查更新
STR_UNKNOWN=未知
STR_UNUSED=未使用
STR_USED=使用
STR_REQUIRED=依赖
STR_GAME_NAME=游戏名称
STR_REGION=地区
STR_CIC_TYPE=Cic Type
STR_ROM_SIZE=游戏大小
STR_SAVE_TYPE=储存类型
STR_TAGS=标签
STR_GAME_PLAYABLE=可游玩的游戏
STR_GAME_INGAME_PLUS=Ingame +
STR_GAME_INGAME_MINUS=Ingame -
STR_GAME_CRASH=Crash
STR_GAME_SLOW=Slow
STR_PLAYABLE_DESC=游戏可以全速运行.
STR_INGAME_PLUS_DESC=游戏可以运行但存在一点故障.
STR_INGAME_MINUS_DESC=可以进入游戏但无法游玩.
STR_CRASH_DESC=不能进入游戏.
STR_SLOW_DESC=游戏可以运行但不能全速.
STR_MENU_LANG=语言
STR_MENU_EXTRA=附加功能
STR_MENU_EMULATION=模拟器
STR_MENU_GRAPHICS=图形
STR_MENU_AUDIO=音频
STR_MENU_INPUT=输入
STR_MENU_OPTIONS=选项
STR_MENU_DEBUGGER=调试器
STR_MENU_CREDITS=Credits
STR_MENU_GLOBAL_SETTINGS=保存全局设置
STR_MENU_GAME_SETTINGS=保存游戏设置
STR_MENU_UI_THEME=UI主题
STR_MENU_MENUBAR=隐藏菜单条
STR_MENU_AUTOUPDATE=启动时自动更新
STR_MENU_COMPAT_LIST=在启动时更新Compat列表
STR_MENU_LOG=控制台日志
STR_MENU_TEX_DUMPER=纹理 Dumper
STR_MENU_DYNAREC=动态重编译
STR_MENU_DYNAREC_CONFIG=动态重编译设置
STR_MENU_CACHED_INTERP=缓存注释器
STR_MENU_INTERP=注释器
STR_MENU_HLE=高仿真
STR_MENU_FRAME_LIMIT=帧数限制
STR_MENU_VIDEO_RATE=同步视频速度
STR_MENU_AUDIO_RATE=同步音频速度
STR_MENU_ASPECT_RATIO=纵横比
STR_MENU_RATIO_UNSTRETCHED=16:9的未拉伸
STR_MENU_RATIO_ORIGINAL=1：1
STR_MENU_BRIGHTNESS=亮度
STR_MENU_TEX_CACHE=纹理缓存
STR_MENU_BILINEAR=双线性滤波器
STR_MENU_MIPMAPS=Mipmaps
STR_MENU_HIRES_TEX=高分辨率纹理
STR_MENU_VRAM=使用VRAM
STR_MENU_WAIT_REND=等待渲染完成
STR_MENU_FILES=文件
STR_MENU_CHEATS=金手指
STR_MENU_SAVE_STATE=即时保存
STR_MENU_LOAD_STATE=即时读取
STR_MENU_RESTART_ROM=重置游戏
STR_MENU_CLOSE_ROM=关闭游戏
STR_MENU_SORT_ROMS=游戏排序
STR_MENU_MP3_INSTR=禁用MP3指令
STR_MENU_REARPAD=使用Rearpad
STR_MENU_CTRL_MAP=控制映射
STR_SORT_A_TO_Z=A to Z
STR_SORT_Z_TO_A=Z to A
STR_DISABLED=禁用
STR_SLOT=Slot
STR_VFLUX_CONFIG=vFlux配置
STR_VFLUX_COLOR=滤镜
STR_VFLUX_ENABLE=启用vFlux
STR_CREDITS_AUTHOR=Port Author
STR_CREDITS_PATRONERS=赞助人:
STR_CREDITS_TRANSLATORS=翻译:
STR_CREDITS_THANKS=特别感谢:
STR_CREDITS_1=xerpi for the initial Vita port
STR_CREDITS_2=MasterFeizz for the ARM DynaRec
STR_CREDITS_3=TheFloW & cmf028 for his contributions to the DynaRec code
STR_CREDITS_4=m4xw for the help sanitizing PIF code
STR_CREDITS_5=Salvy & frangarcj for the help with some bugfixes
STR_CREDITS_6=Inssame for some additions to the UI code
STR_CREDITS_7=That One Seong & TheIronUniverse for the Livearea assets
STR_CREDITS_8=withLogic for the high-res preview assets
STR_CREDITS_9=Rob Scotcher for the Daedalus X64 logo image
STR_CART_ID=Cartridge ID
STR_GFX_UCODE=安装 GFX Microcode
STR_AUDIO_UCODE=安装 Audio Microcode
STR_SYNC=同步
STR_ASYNC=不同步
STR_CONTROLLER=控制器
STR_ACCESSORY=附件
STR_ACCURATE=精确的
STR_FAST=快
STR_DESC_MP3_INSTR=为了更好的性能，禁用MP3指令.
STR_DESC_REARPAD=通过手柄模拟L1/R1/L3/R3 .
STR_DESC_VFLUX=在屏幕上使用一种滤镜.
STR_DESC_VRAM=开启显存使用为了纹理储存.
STR_DESC_WAIT_REND=Makes CPU wait GPU rendering end before elaborating the next frame.\nReduces artifacting at the cost of performances.
STR_DESC_HIRES_TEX=启用外部高分辨率纹理包.
STR_DESC_MIPMAPS=强制为3D渲染生成mipmaps.
STR_DESC_BILINEAR=强制对每个纹理进行双线性过滤.
STR_DESC_CACHE_FAST=缓存永久存储的纹理。改善了性能，但可能会导致严重的故障.
STR_DESC_CACHE_ACCURATE=在每一帧缓存纹理。改进性能，但可能造成小故障.
STR_DESC_CACHE_DISABLED=禁止缓存存储的纹理。减少了以性能为代价的图形故障.
STR_DESC_AUDIO_RATE=加速音频逻辑以匹配帧率.
STR_DESC_VIDEO_RATE=加速视频逻辑以匹配帧率.
STR_DESC_FRAME_LIMIT=限制运行中游戏的帧率.
STR_DESC_HLE=支持对操作系统功能的高级模拟，以获得更好的性能.在一些游戏中可能会导致不稳定.
STR_DESC_INTERP=启用解析器以获得最佳兼容性.
STR_DESC_CACHED_INTERP=支持缓存解析器以获得良好的性能和更好的兼容性.
STR_MENU_DYNAREC_WORDS_OPT=优化存储字节
STR_DESC_DYNAREC=启用动态重新编译以获得最佳性能.
STR_DESC_TEX_DUMPER=启用高分辨率纹理包的纹理转储.
STR_THEME_DARK=黑
STR_THEME_LIGHT=亮
STR_THEME_CLASSIC=经典
STR_REGION_GER=Germany
STR_REGION_USA=中文
STR_REGION_FRA=France
STR_REGION_ITA=Italy
STR_REGION_JAP=Japan
STR_REGION_EUR=Europe
STR_REGION_ESP=Spain
STR_REGION_AUS=Australia
STR_ANTI_ALIASING=抗锯齿
STR_REBOOT_REQ=此更改需要重新启动应用程序才能生效。当前设置将被保存为全局设置，应用程序将重新启动。你想继续吗?
STR_ALERT_GLOBAL_SETTINGS_SAVE=全局设置保存成功!
STR_ALERT_GAME_SETTINGS_SAVE=游戏设置保存成功!
STR_ALERT_GLOBAL_SETTINGS_LOAD=全局设置加载成功!
STR_ALERT_GAME_SETTINGS_LOAD=游戏设置加载成功!
STR_ALERT_STATE_SAVE=即时存档成功!
STR_ALERT_STATE_LOAD=即时读取成功!
STR_BIG_TEXT=Scale UI Texts
STR_ROM_LAUNCH=Launching ?ROMNAME?
STR_CUSTOM_PATH=自定义游戏路径
STR_DLG_CUSTOM_PATH=插入一个自定义的游戏路径
STR_SEARCH=搜索: 
STR_DLG_SEARCH_ROM=通过名字查找游戏
STR_EXTRACTING=提取存档
STR_DOWNLOAD_DATA=下载数据文件
STR_DLG_DOWNLOAD_DATA=下载数据文件
STR_FILTER_BY=筛选条件: 
STR_NO_FILTER=无滤镜
STR_NO_TAGS=无标签
STR_MENU_POST_PROCESSING=后处理
STR_DESC_POST_PROCESSING=允许在最终渲染的场景中应用自定义效果.
STR_NO_POST_PROCESSING=libshacccg.suprx没有正确安装此功能被禁用了.
STR_MENU_OVERLAYS=遮罩
STR_DESC_OVERLAYS=在最终渲染的场景上绘制图像.
STR_DLG_RETRIEVE_NET_PATH=检索网络游戏列表
STR_NET_PATH=网络服务器
STR_DLG_NET_PATH=设置服务器地址
STR_DLG_ROM_LAUNCH=通过服务器获取游戏
STR_GAME_NET=无法获得服务器上游戏.
STR_GAME_LOCAL=本地
STR_GAME_ONLINE=联网
STR_MENU_LEGACY_REND=复古
STR_MENU_MODERN_REND=现代
STR_DESC_LEGACY_REND=基于GL1固定函数管道的原始渲染器.
STR_DESC_MODERN_REND=基于GL2+着色器的现代渲染器. 需要libshacccg.suprx.
STR_PLAYTIME=游玩时间
STR_DLG_NET_BOOT=在开启时检索服务器上的游戏
STR_MENU_DYNAREC_LOOPS_OPT=循环优化

There are a lot of shortcomings in it and I hope it can be optimized.Thank you again!!

**Comment by Rinnegatamante** [comment]
Thanks for this, integrated with: https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/d582cfbd23d76e59b6c82038370a54e22bcf4215 .
Due to the new font having chinese glyphs, loading time for the emulator increased a lot. I may end up adding a new option to enable CJK glyphs in the font only if requested but for now, it should work fine. Font used for CJK glyphs is Arial Unicode.
![immagine](https://user-images.githubusercontent.com/9152710/111906511-1f79eb80-8a51-11eb-8c16-a4354df7327c.png)

**Comment by CHN-Gen** [comment]
Thanks for your work, it's looks so good
