### ISSUE TITLE
[BUG] Scale UI Text crashes the emulator

### ISSUE THREAD

**Issue by DerinQyu** [Rinnegatamante/DaedalusX64-vitaGL#236]
Describe the bug
Was on stable release and yesterday installed the latest nightly then when I tried to open the emulator it crashed on boot. Did a fresh install and found that Scale UI Text was the culprit. 

If you try to use scale ui text the emulator will crash and send you to the live area.

To Reproduce
Steps to reproduce the behavior: just go to Extra menu and try to use the Scale UI Texts option, emulator will crash then.

Expected behavior

Screenshots

Device:
 - Device: [PS Vita 2000]
 - FW:[Enso 3.60]
 - Daedalus Version [ v.0.6(175871) ]

Additional context

**Comment by Rinnegatamante** [comment]
Fixed with: https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/53a2b59b7aabbcc35b12b4cc92283e045a3e7c93
