### ISSUE TITLE
[FEATURE] Roms selector ordering

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL#24]
Describe the bug
Roms are ordered Z-A

To Reproduce
Load roms

Expected behavior
Roms should be A-Z or an option to toggle

Screenshots

Device:
  PCH-2016 

Additional context

**Comment by Rinnegatamante** [comment]
Roms are ordered by last modification date actually and not alphabetically. Roms ordering for several criterias would be a cool addition however.

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/1dd1ec15615a98be62d6dcf5f74836097edb2d78
