### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by kuragehimekurara1** [Rinnegatamante/DaedalusX64-vitaGL#246]
I would like to translate DaedalusX64-vitaGL into Japanese. Does DaedalusX64-vitaGL support translation?

**Comment by Rinnegatamante** [comment]
Yes, you can check this file and provide me with the translated lines: https://github.com/Rinnegatamante/DaedalusX64-vitaGL/blob/master/Data/DaedalusX64/Languages/English.ini

Once it's ready, i can implement it in the app.

**Comment by kuragehimekurara1** [comment]
Do I have to fork this?

**Comment by kuragehimekurara1** [comment]
thank you!  Please wait as we will make a pull request when the translation to Japanese is completed.
