### ISSUE TITLE
[BUG] Ps Vita 1001 Silver model Mischief makers crashes 

### ISSUE THREAD

**Issue by Duly-noted1** [Rinnegatamante/DaedalusX64-vitaGL#249]
Describe the bug
Mischief makers crashes. It happens right at the name entry screen usually although i made it to the professor talking to Merina once. Legacy or modern renderer. Texture caching did let me read a bit of dialog before the crash occurs.

To Reproduce
Steps to reproduce the behavior: Vita 1001 model silver. Henkaku 3.65 installed. I tried running the game with my normal plugins, and I also tried running them with nothing but sd2vita and henkaku installed. Either way I get that 2-12821 error code. Previous builds I never even got to the name screen.

Expected behavior

Screenshots

Device:
 - Device: [e.g. PSP Model or VITA]
 - FW:[e.g. Current System Firmware]
 - Daedalus Version [e.g. 1.1.6]

Additional context

**Comment by Rinnegatamante** [comment]
Not an emulator bug.

**Comment by Duly-noted1** [comment]
Are there any known compatability issues between daedalus and other
plugins? I tried launching it with only the bare essentials and it still
didn't work.

**Comment by Rinnegatamante** [comment]
This is not the place to discuss about specific game issues. https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/26#issuecomment-1107881279
