### ISSUE TITLE
UI hangs if you use the X button to select a menu

### ISSUE THREAD

**Issue by noradninja** [Rinnegatamante/DaedalusX64-vitaGL#25]
Describe the bug
If I select any menu item besides loading a game by pressing the X button, DaedalusX64 freezes

To Reproduce
Select any menu item when DaedalusX64 loads using the X button, the software will lock and you have to close and reload it.
Expected behavior
To be able to use menus to enable/disable audio, graphics options, etc with buttons
Device:
 - Device: PSV Fat
 - FW:3.65
 - Daedalus Version 0.1

Additional context
Menus work fine if you only use the touch screen to interact with them

**Comment by bdacanay** [comment]
That's not a bug. When you press X whatever rom that is highlighted will boot. You probably had the cursor on a rom that crashes the emu, so that's why you experienced that. You select menu items with LT.
