### ISSUE TITLE
[FEATURE] Cheat Engine.

### ISSUE THREAD

**Issue by NicolasMKZ** [Rinnegatamante/DaedalusX64-vitaGL#250]
I would like to see again on PSVita this function which was present on the PSP version if possible.

If this is not possible I would like to find an alternative to be able to cheat.

Thank you !

**Comment by Rinnegatamante** [comment]
Deadalus has already cheats.

**Comment by NicolasMKZ** [comment]
How to do ? 

Please.

Hinata NekoNya.

**Comment by Rinnegatamante** [comment]
Launch a game and access the Cheats  section from the top menubar.
