### ISSUE TITLE
Remap Joysticks?

### ISSUE THREAD

**Issue by DeroPlayz** [Rinnegatamante/DaedalusX64-vitaGL#255]
Hello, this isn't so much of a bug or issue per se so much as it is a request. Is there a way to remap the N64 joystick with the remap files? I have GoldenEye 007, and want to have conventional shooter controls; all movement on one joystick and all camera control on the other. Thanks!

**Comment by Rinnegatamante** [comment]
You can create your own remap configs by creating remap files in ux0:data/DaedalusX64/ControllerConfigs

**Comment by DeroPlayz** [comment]
Thanks, I did know that, but can I modify what inputs go through as the N64
joystick?

**Comment by Rinnegatamante** [comment]
Yes, you can map whatever N64 control to whatever Vita control. You'll find there several already made remap configs you can use as inspiration.

**Comment by DeroPlayz** [comment]
Cool, thanks!

**Comment by DeroPlayz** [comment]
Sorry for pestering you again, but how would I remap, say, the N64 Joystick
to the arrow pad? I don't see the syntax (ie N64.LUp = VITA.Up) for it in
any of the controller config files. Thanks and sorry!

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/DaedalusX64-vitaGL/blob/1758719a8107d3841d88869fa293e84b62d80770/Source/SysVita/Input/InputManagerVita.cpp#L170-L186

https://github.com/Rinnegatamante/DaedalusX64-vitaGL/blob/1758719a8107d3841d88869fa293e84b62d80770/Source/SysVita/Input/InputManagerVita.cpp#L506-L525

These are the list of controls bindable.
