### ISSUE TITLE
[BUG] v0.6 nightly - smash remix 1.3.1 

### ISSUE THREAD

**Issue by GatoXmeansXcat** [Rinnegatamante/DaedalusX64-vitaGL#257]
1. When playing as marina on training mode after doing her normal attacks she gets stuck on the kicks animation forever until someone hits her or i restart. (can't move while in the kicking anim. btw.)
- Happens everytime in training mode but thankfully not in 1p mode. Can't check on android or somewhere else if is a problem with vita or the game.

2. Looks like yellow blocks hitboxes on top of characters model dont show that well like in retroarch for android. In retroarch-android shows only the outline for the yellow hitboxes letting you see the character very well, on the vita is only fully yellow blocks and doesn't show character.
- Most of the graphics options disabled/stock for better performace.

3.  Disabling texture caching freezes the game.
-And just being in the select menu for a while crashes the game.

4. Game always crashes with this after finishing platforms bonus stage with marina (not sure if it does the same with other characters.)

![2023-04-26-005733-656084](https://user-images.githubusercontent.com/131831855/234482574-db5a8067-1527-40f6-bd36-21f8f0b6328d.png)

Device:
 - Vita 1000
 - 3.60 ENSO - i think 1.1
 - Nightly v0.6 (3823a1)

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/509
