### ISSUE TITLE
[BUG] current nightly frequently crashes Zelda oot. Last version I was able to play for long periods of time was version 03.31.23. game is fully completable but there are some graphical glitches that can be bypassed by changing the renderer to modern but doing so in-game crashed app.

### ISSUE THREAD

**Issue by EntertainmentOk8487** [Rinnegatamante/DaedalusX64-vitaGL#260]
Describe the bug

To Reproduce

Expected behavior

Screenshots

Device:
 - Device: [e.g. PSP Model or VITA]
 - FW:[e.g. Current System Firmware]
 - Daedalus Version [e.g. 1.1.6]

Additional context

**Comment by Rinnegatamante** [comment]
Workarounded with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/6bf4b4ae080339e0ab24f4be9929ed7213ea1f8c
