### ISSUE TITLE
[BUG] Black screen appears after loading the ROM. Game runs fine based on input and audio.

### ISSUE THREAD

**Issue by zachary-cauchi** [Rinnegatamante/DaedalusX64-vitaGL#262]
Describe the bug
The romhack "Shotgun Mario 64" causes the emulator to not render the game properly. The romhack appears in the list correctly and can be loaded. When clicking to load the game, the screen turns black and the "loading rom" message in the bottom of the screen remains stuck on-screen. When tapping the screen to try open the menu, it doesn't respond. The game plays audio and reacts as expected to the sounds of the game, but no other screen changes happen.

To Reproduce
* Place the Shotgun Mario 64 rom in the configured roms folder.
* Open Daedalusx64.
* Click on the Shotgun Mario 64 menu item to load the rom.
* The screen should turn black and stay frozen.

Expected behavior
The game should load as expected but the loading screen should disappear. The loading message should disappear, the game should be visible, and the emulator menu should show up when tapping on the screen.

Screenshots
![black screen](https://github.com/Rinnegatamante/DaedalusX64-vitaGL/assets/23012377/4030f2b5-9cf8-4daa-9a55-adb2bace98a9)

Device:
 - Device: PSVita OLED (No 3G)
 - FW: Firmware version 3.65
 - Daedalus Version Self-compiled from commit 6bf4b4a

Additional context
This was also tested on the latest nightly release from VitaDB.
This was last tested on 2023/11/16

**Comment by Rinnegatamante** [comment]
This is not the place for game dependant reports. Compatibility List is where this should be posted. Also not a bug, simply the romhack is not supported.
