### ISSUE TITLE
[FEATURE] Default clocks speed

### ISSUE THREAD

**Issue by teakhanirons** [Rinnegatamante/DaedalusX64-vitaGL#27]
Currently, default clock speeds are at the lowest, making an overclock plugin necessary to even make anything playable. While an overclock plugin is of importance because of the 500 MHz CPU clock speed feature implemented in most of them, default clocks should still be set to the highest natively available ones, like the PSP builds do as seen [here](https://github.com/Rinnegatamante/DaedalusX64-vitaGL/blob/ebc404883e757afae65fd1df42721f72bb2ace74/Source/SysPSP/main.cpp#L162).
Clock speed set functions do have userland counterparts as seen [here](https://docs.vitasdk.org/group__ScePowerUser.html#ga60e340ae4ae835b6504880efe9ce2069).

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/8838985fe1d454e45294e9a7ad353f91f9919937
