### ISSUE TITLE
[FEATURE] BoxArts for each rom and info display

### ISSUE THREAD

**Issue by animekai** [Rinnegatamante/DaedalusX64-vitaGL#28]
Would be nice to have the boxart covers when hovering over a rom, some preview captures, and also some info like the version, the region ,size, format etc.

**Comment by Rinnegatamante** [comment]
Possible but definitely not a priority

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/a4180abb31f8c505aaf9e080ef226267abfaefd7
