### ISSUE TITLE
[FEATURE] 60FPS hack or frame interpolation

### ISSUE THREAD

**Issue by animekai** [Rinnegatamante/DaedalusX64-vitaGL#29]
Would be nice to have some option to force 60fps on 30fps games, with some kind of frame interpolation.

But there are some native n64 games that runs on 60fps, maybe if we run roms at native resolution maybe it can be more frames, like a graphic or performance selector as some ps4 games have.

**Comment by Rinnegatamante** [comment]
You can disable Frame Limit in Emulation options to have games go at higher framerate than they were thought to be played on. This would however most likely break game timings.
