### ISSUE TITLE
[BUG] GUI Menu doesn't works at startup

### ISSUE THREAD

**Issue by animekai** [Rinnegatamante/DaedalusX64-vitaGL#31]
Describe the bug

When i open the daedalusx64 app, the menu doesn't work, i have to go ingame to any rom and then use the touchpad to click on the menus, otherwise they dont work at startup.

To Reproduce
Open Daedalusx64, click on any menu doesn't work, click on a rom to play then use touchpad to navigate tu the menu and click, then it works

Expected behavior
The menu should work and be clickeable from startup

Screenshots

Device:
 - Device: PSTV
 - FW: 3.60
 - Daedalus Version 0.1

Additional context

[Daedalus menu bug.zip](https://github.com/Rinnegatamante/DaedalusX64-vitaGL/files/4566706/Daedalus.menu.bug.zip)

I include a mp4 video showing the bug in progress, as u can see i cant select anything at startup bue going ingame and then navigation to menu it works

**Comment by Rinnegatamante** [comment]
Menu does work just fine here (tested on both PSTV and PSVITA). You can either press L or tap when you're on one of the menu entries.

**Comment by animekai** [comment]
did you watch the video i've attached? i tried navigating throught the entries but the menu was not responding, i have to go in a game, and then the menu works; maybe is just me.

**Comment by animekai** [comment]
ok i have discovered the problem, i was trying to navigate and click the menu just with analog and pressing x, when is suposed to use the virtual touchpad to navigate and then make clicks with the virtual touchpad, without it, it doesnt do nothing than move the mouse cursor, there is any way to make it click without entering in touchpad mode?

**Comment by SamuEDL98** [comment]
Move with the dpad and press X to enter the game.

**Comment by Rinnegatamante** [comment]
Seems somehow linked to https://github.com/Rinnegatamante/DaedalusX64-vitaGL/issues/25 . Gonna close this for now, probably solving the first will fix this too.
