### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by hardlevel** [Rinnegatamante/DaedalusX64-vitaGL#36]
Sorry for this dumb question, but I can`t find any information in wololo or psx-place or here about it

I installed the vpk with vitashell, opened and ok, but how can I open the roms?

**Comment by Rinnegatamante** [comment]
Install the vpk, extract the data files in ux0:data and place roms in the Roms folder inside ux0:data/DaedalusX64.

**Comment by geedeo-cloud** [comment]
Could you add this information in readme?
is there a preferred file type?
eg:  .n64, .v64, .z64.
