### ISSUE TITLE
Roms don't load, softlocks Daedalusx64 app

### ISSUE THREAD

**Issue by SweetStorm** [Rinnegatamante/DaedalusX64-vitaGL#38]
I'm not new to emulators by any means, but the Vita has always puzzled me a bit. I have a fat 1000 model vita, on 3.60 enso. Whenever i try to load up a rom on Daedalusx64, the app freezes and never loads anything. It just stays at the main screen, no matter what settings I have. I've tried rebooting, reloading taihen, and restored the vita's database through the vita's recovery menu. Nothing has made a difference. 
Can you give me any insight to what I might have to do? I've been waiting years for Daedalus to become Vita-native and I'm just inches away from it :( 
Thanks for any help you provide, and great job on everything!

**Comment by SeongGino** [comment]
Mind explaining what _exactly_ have you tried? This includes:

- Roms used
- Rom formats
- Dynarec On/Off
- Audio On (Synchronous)/Off

Audio in particular can cause many games to not boot at the moment, so it's imperative you try again one piece at a time.

**Comment by SweetStorm** [comment]
> Mind explaining what _exactly_ have you tried? This includes:
> 
> * Roms used
> * Rom formats
> * Dynarec On/Off
> * Audio On (Synchronous)/Off
> 
> Audio in particular can cause many games to not boot at the moment, so it's imperative you try again one piece at a time.
> 
> And if you don't already know, you don't use the mouse cursor to select games; it's D-pad + X.

Thanks for your help! After testing everything I finally found the issue, my roms somehow got corrupted. It now works like a charm :) Thanks again! 
Anyone else with this weird problem, please check your roms first lol
