### ISSUE TITLE
Frame skip Stutter

### ISSUE THREAD

**Issue by Muhamed-Reyad** [Rinnegatamante/DaedalusX64-vitaGL#40]
I'm not sure if this feature is ready yet, but when i enable frame skip on any mode i get stuttering screen effect that are sometimes unplayable.

I apologize If this isn't the place to post this to ask for help..

**Comment by Rinnegatamante** [comment]
That's cause, at the moment, emulator is fully CPU bounded meaning frameskip will only make the game playing slower.
