### ISSUE TITLE
[BUG]Shading regression in latest nightly

### ISSUE THREAD

**Issue by noradninja** [Rinnegatamante/DaedalusX64-vitaGL#42]
It appears there is a regression in the latest nightly (05/05/20). Some surfaces appear to lose their vertex coloring/lighting intermittently- usually when they get close to the camera. 

To Reproduce
Use latest nightly to load a ROM, move camera. 

Device:
 - Device: Vita 1000
 - FW:3.65 Enso
 - Daedalus Version: Nightly (05/05/2020)
![19369B04-BA7E-4D2C-8BAC-080A24C63B8B](https://user-images.githubusercontent.com/6692990/81106782-299c0580-8ee4-11ea-825a-8ccc83a318ca.jpeg)
![098A0849-846C-47C0-9696-43B127E34322](https://user-images.githubusercontent.com/6692990/81106787-2acd3280-8ee4-11ea-926c-ede1549d64aa.jpeg)
![74675EFF-963E-4462-9678-FBA4295FEF0B](https://user-images.githubusercontent.com/6692990/81106794-2bfe5f80-8ee4-11ea-8801-d0dd31dc278c.jpeg)
![10C49022-4255-4F36-8BCF-F3A3D87D9E70](https://user-images.githubusercontent.com/6692990/81106796-2c96f600-8ee4-11ea-8e97-054b48b5a846.jpeg)

**Comment by Rinnegatamante** [comment]
Commit that regressed this is https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/beaaa75c766f8778243e3382505f4b2c1368f1b8 . Probably related to the colorAdjuster code changes.

**Comment by noradninja** [comment]
Figured, just reported in case you hadn’t picked it up in testing.

**Comment by noradninja** [comment]
Closing as issue is resolved in version 0.2.
