### ISSUE TITLE
[BUG] SaveState in games that are not in rom.ini

### ISSUE THREAD

**Issue by SamuEDL98** [Rinnegatamante/DaedalusX64-vitaGL#46]
**Bug:**
The games that are not in rom.ini, share savestates with the rest of the games that are not there.
Since when you create the savestate, you create it without a name.

**Screenshots**
https://ibb.co/3f5zjWn

**Device:**
 - Device: Vita 1000
 - FW: 3.65 h-encore enso
 - Daedalus Version 0.2

**Comment by Rinnegatamante** [comment]
That's not a bug. You're supposed to add entries for romhacks in roms.ini.
