### ISSUE TITLE
N64 Cheat Support

### ISSUE THREAD

**Issue by bdacanay** [Rinnegatamante/DaedalusX64-vitaGL#51]
I would like to request the use of cheats with the Vita version. There is already a .cht file in the PSP version of Daedalus if that helps. Could add cheats for widescreen hacks, game fixes, unlockables, etc. Thank you!

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/ee26d9874c095c79aa86762ea17d575dde994a55

**Comment by Smoker1** [comment]
Cheats start working, but at some point, they stop completely, even when they are still Enabled.

Also, what Cheats are Compatible? Example.....
Monsters Don't Hurt Mario,=0,A033B197-0001 <- In Cheat File
Dont Hurt Mario-Falling = E8870584 5942+E98708D0 504F - Found on PJ64 (Project64) Cheat File and another Cheat Website.
