### ISSUE TITLE
Translations support

### ISSUE THREAD

**Issue by jona82** [Rinnegatamante/DaedalusX64-vitaGL#53]
the first thing you are incredible and the whole team of the emulator.
it would be possible to translate the emulator into other languages.
for example Spanish.
thanks and regards.

**Comment by chronoss09** [comment]
Good idea :+1:

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/d52a15f2c84c5601872e332ce7e66f919d32d77b

**Comment by jona82** [comment]
Thank you very much for your good work and making the impossible come
true. A strong greeting from Spain.
Rinnegatamante and company.
