### ISSUE TITLE
[BUG] Load save files for modified/patched roms

### ISSUE THREAD

**Issue by diegorocha2007** [Rinnegatamante/DaedalusX64-vitaGL#57]
Hello!
I am using some patches for widescreen 16:9 I found online, like the ones below:
https://www.youtube.com/watch?v=NjJk5dvp118&t=78s

https://www.youtube.com/watch?v=hRS4WWOptT4

https://www.youtube.com/watch?v=RHO3fTJP3lk

The patched roms work just fine, the thing is, the emulator doesn't seem to load saves for these roms.
I don't know how I could add it manually, as it seems like the save files are created and stored in the SaveGames/ folder, it's just a matter of making the emulator load them.

I know it's not an urgent matter, but if you could check this out later on, it would be much appreciated.

**Comment by Rinnegatamante** [comment]
Add related entries to roms.ini for said roms.

**Comment by diegorocha2007** [comment]
I'm sorry but adding the entries alone doesn't seem to work. Is there an algorithm I'm missing?
Again, sorry to bother you, I'm just getting frustrated I can't solve this on my own.

**Comment by Rinnegatamante** [comment]
I've added CRC showing so you can grab said info without the need of another emulator.

**Comment by diegorocha2007** [comment]
Thanks for the help @Bean5ta 
And thanks for adding CRC showing @Rinnegatamante 
I successfully managed to add the entry for the modified rom, and confirmed the saves are loading as intended.
Problem solved, thank you guys!
