### ISSUE TITLE
[BUG] Upgrade zlib to 1.2.11

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL#61]
Describe the bug
Running cppcheck it shows a number of issues with zlib.
The current version is zlib 1.2.8 and the latest release is zlib 1.2.11

The site also states 
Version 1.2.11 has these key improvements over 1.2.10:

    Fix deflate stored bug when pulling last block from window
    Permit immediate deflateParams changes before any deflate input 

Due to the bug fixes, any installations of 1.2.9 or 1.2.10 should be immediately replaced with 1.2.11.

Version 1.2.10 has these key improvements over 1.2.9:

    Fix bug in deflate_stored() for zero-length input
    Fix bug in gzwrite.c that produced corrupt gzip files 

Version 1.2.9 has these key improvements over 1.2.8:

    Improve compress() and uncompress() to support large lengths
    Allow building zlib outside of the source directory
    Fix bug when level 0 used with Z_HUFFMAN or Z_RLE
    Fix bugs in creating a very large gzip header
    Add uncompress2() function, which returns the input size used
    Dramatically speed up deflation for level 0 (storing)
    Add gzfread() and gzfwrite(), duplicating the interfaces of fread() and fwrite()
    Add crc32_z() and adler32_z() functions with size_t lengths
    Many portability improvements 

So there might be more issues here with the lib.

Hopefully it is as easy as replacing the dir and rebuilding.

**Comment by Rinnegatamante** [comment]
Used zlib is the one inside vitasdk, that one should be updated instead (on vdpm).

**Comment by Sarkie** [comment]
According to this, it should be 1.2.11 ?
https://github.com/vitasdk/packages/blob/master/zlib/VITABUILD

**Comment by Rinnegatamante** [comment]
Yes, closing this then.
