### ISSUE TITLE
[FEATURE] 16:9 Aspect Ratio Hack

### ISSUE THREAD

**Issue by bielgiroto** [Rinnegatamante/DaedalusX64-vitaGL#68]
In the PSP version we used to have an option that allowed us to play with an widescreen hack for the games instead of simply stretching them.

I remember being very nice to use, would be very cool bringing this option to the Vita version.

(I love this project though, @Rinnegatamante your work is awesome)

**Comment by Rinnegatamante** [comment]
PSP build didn't have any widescreen hack btw.

**Comment by Rinnegatamante** [comment]
What PSP build offered in that regards has been implemented with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/8ad2580f903150746261560a84930736e1535cf2

**Comment by bielgiroto** [comment]
Wow that was fast!!
Thank you so much!! It isn't perfect, but dude! Mario 64 looks very nice in fullscreen without stretching
