### ISSUE TITLE
[FEATURE] Adding support of archived roms

### ISSUE THREAD

**Issue by Rameron** [Rinnegatamante/DaedalusX64-vitaGL#73]
Hi.
It's absolutely not critical, but size of rom for N64 can reach 64 MB, so it will be great to do support of zipped roms for emulator for storing a lot of them in the future.
Is this planned to be added?
Thanks.

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/a00956750732afe8142626c6f6f968061b2b1e0d
