### ISSUE TITLE
[FEATURE] Allow Rendering at Original Resolution

### ISSUE THREAD

**Issue by Clector** [Rinnegatamante/DaedalusX64-vitaGL#77]
Nintendo 64 games on real hardware use 240p or 480i (288p and 576i in PAL), most games usually use 240p.
It'll be nice to have an option  to render the graphics in their original resolution of 240p in games that use it, while it being scaled to 2x or so for the screen.

**Comment by Rinnegatamante** [comment]
Aspect Ratio -> Original (?)

**Comment by Clector** [comment]
What I mean is for the internal resolution to be the original one, DaedalusX64 seems to use a higher internal resolution than the original one at least in 240p games (I haven't tried 480i titles).
Here's an example.
###  - 240p:
![Project64 2020-05-17 15-45-18-07](https://user-images.githubusercontent.com/27870718/82159776-62c66500-9856-11ea-9d52-a99c208b459f.png)
### - DaedalusX64 Vita:
![2020-05-17-154807](https://user-images.githubusercontent.com/27870718/82159794-838eba80-9856-11ea-81c6-6e5b3b10d106.png)

**Comment by Rinnegatamante** [comment]
I don't see any good reason to play a game at a lower internal res. This would also require an huge amount of work for literally just downsides.

**Comment by bielgiroto** [comment]
Well, lowering the res would probably make the games run faster, but the performance with resolution the way it is now it's very next to full speed. With some more time of optimisation we can get it running at a great fps and gorgeous native 544p graphics istead of 240p ones

**Comment by Rinnegatamante** [comment]
Resolution doesn't affect framerate at all.
