### ISSUE TITLE
Cheats Stop Working when Entering new Area[BUG]

### ISSUE THREAD

**Issue by Smoker1** [Rinnegatamante/DaedalusX64-vitaGL#79]
When you Enable a Cheat, it will be working. However, once you enter a new Area, it will stop, even though it is still Enabled.
Device:
 - Device: [e.g. PSP Model or VITA] Vita
 - FW:[e.g. Current System Firmware] 3.65 Enso
 - Daedalus Version [e.g. 1.1.6] 16 May Nightly

**Comment by Rinnegatamante** [comment]
This sounds more a per game issue and not a generic cheat issue.
