### ISSUE TITLE
[FEATURE] Save emulator settings

### ISSUE THREAD

**Issue by bielgiroto** [Rinnegatamante/DaedalusX64-vitaGL#80]
It's a little boring having to setup the emulator options everytime we open it :/

A system that remember our last settings, or even one that remembers each game settings would be very cool, if we consider that almost every n64 game need specific settings that doesn't fit in other games. 

For example: 16:9 unstretched option works fine with Mario 64 and Zelda, but Paper mario and F-Zero X don't work that well with it.

Mario 64 can use the texture caching option for better performance, but in the Zelda games, the text gets glitchy with this turned on, you get the idea.

But anyway, even if just a simple system to remember our last settings in general gets added, it will be very appreciated as well :)

**Comment by DerpyBubblez** [comment]
#16
