### ISSUE TITLE
Configuration list in compatibility list

### ISSUE THREAD

**Issue by eze92** [Rinnegatamante/DaedalusX64-vitaGL#81]
I know it is not the place to put this but I did not find another ... reading one of the comments of one of the requirements that asked that the settings of the games can be saved because not everyone takes them well, it occurred to me that it would be good to open a section in the compatibility github or another one, where each user can say what is the most optimal configuration that I manage to use so that the game runs correctly / better

**Comment by Rinnegatamante** [comment]
Technically said config should be reported in the Issues on the Compatibility List despite not everyone doing so.
