### ISSUE TITLE
[BUG] Joystick misbehaviour

### ISSUE THREAD

**Issue by pablojrl123** [Rinnegatamante/DaedalusX64-vitaGL#85]
Describe the bug
Left and upwards movement of the left joystick in-game don't work. When moving the joystick to the left or up the input is incorrectly translated as a right or down movement, respectively. The joystick does move the cursor correctly in DaedalusX64-vitaGL user interface.

To Reproduce
Just start a ROM, the bug seems to affect every game.

Device:
 - Device: VITA
 - FW: 3.65 HENkaku-2
 - Daedalus Version: master-branch 05/19/2020 - 16:12

**Comment by Rinnegatamante** [comment]
Update math-neon.
