### ISSUE TITLE
[FEATURE] Filter by label

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL#86]
Describe the bug
Be able to filter by label, e.g. filter by "playable" and also filter by "no label" so easier to have a list of games that need to have a compatibility issue created

Expected behavior
In the Options, menu, have an option, "Filter -> Playable, InGame"

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/232e559f6ea07400d691f85b11e573966a32be11
