### ISSUE TITLE
[BUG] Not utilizing all the cores

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL#88]
Describe the bug
It seems that emulation only really utilizes cores 2 and 3 (out of 1 to 4)
By pressing Select to kill the screen, it'll swap between 2 and 3 and use 100% cores.

To Reproduce
Install PSVShell and show all the cores
When emulating all cores are used.
It seems to show only 2 or 3 will go high.

Expected behavior
Expecting it to use all the cores and spread the load.
Checking other games this seems consistent

Screenshots
Mario Core 2 high
![image](https://user-images.githubusercontent.com/283203/82553420-e1bfe400-9b5b-11ea-91e5-298c0946048f.png)

Mario Core 3 high
![image](https://user-images.githubusercontent.com/283203/82553603-424f2100-9b5c-11ea-9449-fc09f2b8b9d6.png)

(Press select a few times)
Mario Core 2 high
![image](https://user-images.githubusercontent.com/283203/82553631-52ff9700-9b5c-11ea-9cdb-c9120ebf848b.png)

Assassin's Creed all spread
![image](https://user-images.githubusercontent.com/283203/82553457-f43a1d80-9b5b-11ea-8f68-3569e4cfd839.png)

vitaQuake all spread
![image](https://user-images.githubusercontent.com/283203/82553477-02883980-9b5c-11ea-906e-5b9b8444c6d1.png)

vitaQuakeII all spread
![image](https://user-images.githubusercontent.com/283203/82553557-2e0b2400-9b5c-11ea-8023-d5a714c85515.png)

vitaQuakeIII all spread
![image](https://user-images.githubusercontent.com/283203/82553522-1af85400-9b5c-11ea-813c-63dd4b669e74.png)

Eduke32 all spread
![image](https://user-images.githubusercontent.com/283203/82553536-2481bc00-9b5c-11ea-8050-c525d7d92540.png)

**Comment by Sarkie** [comment]
This is probably known, but just wanted to track it or wonder what's happening. Thanks

**Comment by Rinnegatamante** [comment]
Daedalus is a single threaded emulator. Also every single hb port you reported doesn't use other cores too.
