### ISSUE TITLE
[BUG] Donald Duck: Quack Attack & Rayman 2 Game Logic issues

### ISSUE THREAD

**Issue by norus212** [Rinnegatamante/DaedalusX64-vitaGL#90]
Severity - Medium 
Probability - High

This possibly applies to other similar games but the title Donald Duck Quack Attack has an issue when Donald is interacting with 2D sprites such as stars or toy books. The general Enviroment is 3D and so is Donald. He interacts with 2D sprite elements and normally picks them up. It seems that he only passes through them without properly registering the collision.

Repro:
1. Start the emulator on latest build.
2. Load donald duck quack attack rom
3. Start any 3D / 2.5 World 
4. Run through stars
OR
Wait for the Demo to begin after booting the title (donald runs through stars in the demo and can be seen they don't work properly)

Expected behavior
Donald goes through the 2D sprites / has proper collision with them picking the objects up

Device:
 - Device: PS Vita Oled

**Comment by Rinnegatamante** [comment]
That's an issue with game logic, it has nothing to do with 2D or 3D graphics. Rayman 2 (same engine) has game logic issues too (uninteractable triggers etc).

**Comment by norus212** [comment]
Would this get fixed globally or does each title need individual fixing?

**Comment by Rinnegatamante** [comment]
Most likely the involved issuees are linked. Those kind of issues btw are present (under some extents) on other emulators too so if they'll ever fix those, probably the changes could be adapted for Daedalus too (example: https://github.com/mupen64plus/mupen64plus-core/issues/724 )

**Comment by Rinnegatamante** [comment]
This is now fixed.
