### ISSUE TITLE
[FEATURE] Post-processing Shaders

### ISSUE THREAD

**Issue by crazy2k4** [Rinnegatamante/DaedalusX64-vitaGL#93]
is posible add this feature?

**Comment by Rinnegatamante** [comment]
Some more details? I don't even know what are you talking about.

**Comment by crazy2k4** [comment]
sorry for my english,i'm spanish xD
i'm try explain:scanlines mamergb is a overlay for retroarch,simulates crt scanlines,in psvita oled,looks very nice with this overlay activated,and reduce color saturation

**Comment by bielgiroto** [comment]
Those post-processing shaders cause a lot of slowdowns on retroarch, i think that if we add overlays support would be better.

The graphics already look very sharp and good, high-res texture may be added in the future, if we add an overlay system, just like in Retroarch we could remove the black borders in games that don't work great with the 16:9 unstretched option, and at the same time, we could have scanlines at the same way we have with the shaders.

Considering that on retroarch, when we add a overlay, it simply adds a png image with transparency to the screen, we can have borders and some nice visual effetcs at the same time without hurting the overall performance.

Just an idea though, you guys decide it.
(I think we should focus on fixing the performance and the graphics in general, we have a lot of "not essential" ideas already)

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/e0893d26c46c58f1bbc1bd10ab182bea7d6ad4a0
