### ISSUE TITLE
[FEATURE] Rom name in title

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL#94]
Describe the bug
When testing roms, I forget what I'm playing, and the only way to find out it's close the ROM.

As there's enough room in the title, I'd like to request in put there.

To Reproduce

Expected behavior

Screenshots

Device:
 - Device: [e.g. PSP Model or VITA]
 - FW:[e.g. Current System Firmware]
 - Daedalus Version [e.g. 1.1.6]

Additional context

**Comment by Rinnegatamante** [comment]
I don't get what you mean.

**Comment by Sarkie** [comment]
When playing, the menu bar,  I'd like the name of the game between Extra and the FPS counter

**Comment by bielgiroto** [comment]
I don't really think we need this at all, how do you forget the game's name that you're playing??? It's completely pointless

**Comment by bdacanay** [comment]
Looks like he's using the PSP build...

**Comment by Sarkie** [comment]
@bielgiroto @bdacanay 
As stated when I'm testing roms, I don't have a clue what I'm playing as I have every single N64 ROM in my collection 

And there's no easy way for me to remember.

Thanks for your insight though.

**Comment by Rinnegatamante** [comment]
I don't like that option, would make the menubar unreadable. It also sounds like a pointless feature indeed.

**Comment by Sarkie** [comment]
Cheers
