### ISSUE TITLE
[BUG] Make ordering case insensitive

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL#95]
Describe the bug
Ordering is case sensitive, so lower case roms

To Reproduce
Order the roms with a-z 
Lower case roms are ordered at the end

Expected behavior

Screenshots

Device:
 - Device: [e.g. PSP Model or VITA]
 - FW:[e.g. Current System Firmware]
 - Daedalus Version [e.g. 1.1.6]

Additional context

Or a different solution, is order by game name not ROM filename

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/f4515f5386c9903889c9e3171add45b75860f99e

**Comment by Rinnegatamante** [comment]
Seems like in some casees it causes issues, reverting the change for now and reopening this.

**Comment by Sarkie** [comment]
Ok, also don't know if you should order by game name read by the ROM too instead of the filename

**Comment by Rinnegatamante** [comment]
Done with: https://github.com/Rinnegatamante/DaedalusX64-vitaGL/commit/05155eab2a6147df90d14888f9ebdca3363a7287
